package service

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"html/template"
	"strings"

	"akademi-bimbel/internal/model"
	"akademi-bimbel/internal/repository"

	"github.com/google/uuid"
	"github.com/minio/minio-go/v7"
)

// QuestionBundleNeededPayload is the outbox event payload for async question bundle PDF generation.
type QuestionBundleNeededPayload struct {
	BundleID uuid.UUID `json:"bundle_id"`
}

const questionBundlePDFContentType = "application/pdf"

var questionBundleHTMLTemplate = template.Must(template.New("question_bundle").Parse(`<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
@page { size: A4; margin: 16mm 14mm; }
body { font-family: Inter, Arial, sans-serif; color: #111827; font-size: 12px; line-height: 1.45; }
.cover { page-break-after: always; display: flex; min-height: 240mm; flex-direction: column; justify-content: center; text-align: center; }
.brand { font-size: 13px; letter-spacing: .08em; color: #4f46e5; text-transform: uppercase; font-weight: 700; }
h1 { margin: 10px 0 4px; font-size: 30px; }
.muted { color: #6b7280; }
.test-title { page-break-before: always; border-bottom: 2px solid #111827; padding-bottom: 8px; margin-bottom: 18px; }
.question { break-inside: avoid; margin: 0 0 18px; }
.q-head { font-weight: 700; margin-bottom: 6px; }
.q-body { margin-bottom: 8px; }
.q-body img { max-width: 100%; }
.options { margin: 8px 0 0; padding: 0; list-style: none; }
.options li { margin: 4px 0; }
.answer-key { margin-top: 8px; padding: 8px 10px; background: #f3f4f6; border-left: 3px solid #4f46e5; }
.answer-key-title { font-weight: 700; margin-bottom: 4px; }
.blank-list { margin: 4px 0 0 18px; padding: 0; }
.media { max-width: 100%; margin: 8px 0; }
.audio-note { display: inline-block; margin: 6px 0; padding: 4px 8px; border-radius: 999px; background: #fff7ed; color: #9a3412; font-weight: 700; }
.key-banner { position: fixed; top: 8mm; left: 14mm; right: 14mm; text-align: center; color: #b91c1c; font-weight: 800; letter-spacing: .08em; }
.footer { position: fixed; bottom: 7mm; left: 14mm; right: 14mm; display: flex; justify-content: space-between; color: #6b7280; font-size: 10px; }
</style>
</head>
<body>
{{if .IncludeAnswerKey}}<div class="key-banner">KUNCI JAWABAN — JANGAN DIBAGIKAN</div>{{end}}
<div class="footer"><span>Bundle {{.BundleID}}</span><span>Generated by {{.CreatedBy}}</span></div>
<section class="cover">
  <div class="brand">Abak Academy</div>
  <h1>{{.Title}}</h1>
  <p class="muted">{{if .IncludeAnswerKey}}Naskah soal + kunci jawaban{{else}}Naskah soal{{end}}</p>
  <p class="muted">Generated bundle ID: {{.BundleID}}</p>
</section>
{{range .Tests}}
<section>
  <div class="test-title">
    <h2>{{.Title}}</h2>
    <div class="muted">{{.Subject}} • {{.Topic}} • {{.DurationMinutes}} menit</div>
  </div>
  {{range .Questions}}
  <article class="question">
    <div class="q-head">Soal {{.Number}} <span class="muted">({{.Format}})</span></div>
    <div class="q-body">{{.BodyHTML}}</div>
    {{if .PromptStatements}}<ol class="blank-list">{{range .PromptStatements}}<li>{{.}}</li>{{end}}</ol>{{end}}
    {{if .ImageURL}}<img class="media" src="{{.ImageURL}}" alt="Gambar soal {{.Number}}">{{end}}
    {{if .HasAudio}}<div class="audio-note">🔊 Soal ini memiliki audio — diputar oleh pengawas</div>{{end}}
    {{if .Options}}
    <ol class="options" type="A">
      {{range .Options}}<li>{{.Key}}. {{.Text}}{{if .ImageURL}}<br><img class="media" src="{{.ImageURL}}" alt="Gambar opsi {{.Key}}">{{end}}</li>{{end}}
    </ol>
    {{end}}
    {{if $.IncludeAnswerKey}}
    <div class="answer-key">
      <div class="answer-key-title">Kunci / rubrik</div>
      {{if .CorrectOptions}}<div>Opsi benar: {{.CorrectOptions}}</div>{{end}}
      {{if .CorrectAnswer}}<div>Jawaban: {{.CorrectAnswer}}</div>{{end}}
      {{if .AcceptedAnswers}}<div>Jawaban diterima: {{.AcceptedAnswers}}</div>{{end}}
      <div>Poin benar: {{.PointCorrect}} • Poin salah: -{{.PointWrong}}</div>
      {{if .Blanks}}
      <div>Isian:</div>
      <ol class="blank-list">{{range .Blanks}}<li>{{.}}</li>{{end}}</ol>
      {{end}}
      {{if .Statements}}
      <div>Pernyataan:</div>
      <ol class="blank-list">{{range .Statements}}<li>{{.}}</li>{{end}}</ol>
      {{end}}
      {{if .Explanation}}<div>Pembahasan: {{.Explanation}}</div>{{end}}
      {{if not .HasKeyMaterial}}<div class="muted">Tidak ada kunci eksplisit untuk format ini.</div>{{end}}
    </div>
    {{end}}
  </article>
  {{end}}
</section>
{{end}}
</body>
</html>`))

type questionBundleHTMLData struct {
	Title            string
	BundleID         string
	CreatedBy        string
	IncludeAnswerKey bool
	Tests            []questionBundleTestHTMLData
}

type questionBundleTestHTMLData struct {
	Title           string
	Subject         string
	Topic           string
	DurationMinutes int
	Questions       []questionBundleQuestionHTMLData
}

type questionBundleQuestionHTMLData struct {
	Number           int
	Format           string
	BodyHTML         template.HTML
	ImageURL         string
	HasAudio         bool
	PromptStatements []string
	Options          []questionBundleOptionHTMLData
	CorrectOptions   string
	CorrectAnswer    string
	AcceptedAnswers  string
	Blanks           []string
	Statements       []string
	Explanation      string
	PointCorrect     string
	PointWrong       string
	HasKeyMaterial   bool
}

type questionBundleOptionHTMLData struct {
	Key      string
	Text     string
	ImageURL string
}

// EnqueueQuestionBundle creates a new question bundle request (async). It validates the actor,
// scope existence, and variant; then atomically creates the bundle, inserts the outbox event,
// and records audit evidence — all in one transaction. POST returns 202 Accepted.
func (s *Service) EnqueueQuestionBundle(ctx context.Context, actor uuid.UUID, actorRole string, examID, testID *uuid.UUID, includeAnswerKey bool) (*model.QuestionBundle, error) {
	if !HasCapability(actorRole, "question-bundles:*") {
		return nil, ErrForbidden
	}
	if (examID == nil && testID == nil) || (examID != nil && testID != nil) {
		return nil, fmt.Errorf("%w: exactly one of exam_id or test_id must be provided", ErrValidation)
	}

	tx, err := s.storeRepo.BeginTx(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	if examID != nil {
		if _, err := s.storeRepo.GetExamByID(ctx, *examID); err != nil {
			return nil, err
		}
	} else if testID != nil {
		if _, err := s.storeRepo.GetTestByID(ctx, *testID); err != nil {
			return nil, err
		}
	}

	variant := "naskah"
	if includeAnswerKey {
		variant = "kunci"
	}

	bundleID := uuid.New()
	bundle := &model.QuestionBundle{
		ID:        bundleID,
		ExamID:    examID,
		TestID:    testID,
		Variant:   variant,
		Status:    "queued",
		CreatedBy: actor,
	}
	if err := s.storeRepo.CreateQuestionBundleTx(ctx, tx, bundle); err != nil {
		return nil, err
	}
	if err := s.storeRepo.InsertOutboxEvent(ctx, tx, "question_bundle", bundleID, "QuestionBundleNeeded", QuestionBundleNeededPayload{BundleID: bundleID}); err != nil {
		return nil, err
	}

	actorStr := actor.String()
	auditMeta := map[string]any{"bundle_id": bundleID.String(), "variant": variant}
	if examID != nil {
		auditMeta["exam_id"] = examID.String()
	}
	if testID != nil {
		auditMeta["test_id"] = testID.String()
	}
	if err := s.storeRepo.InsertAuditLogMeta(ctx, tx, &actorStr, "question_bundle", bundleID.String(), "question_bundle.request", auditMeta); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return bundle, nil
}

// GenerateQuestionBundlePDF renders and stores a requested bundle. It is safe for
// the outbox worker to retry: ready/failed bundles are terminal no-ops, queued
// bundles are claimed, and processing bundles are resumed after a worker crash.
func (s *Service) GenerateQuestionBundlePDF(ctx context.Context, bundleID uuid.UUID) error {
	bundle, err := s.storeRepo.GetQuestionBundleByID(ctx, bundleID)
	if err != nil {
		return err
	}
	if bundle.Status == "ready" || bundle.Status == "failed" {
		return nil
	}
	if bundle.Status == "queued" {
		tx, err := s.storeRepo.BeginTx(ctx)
		if err != nil {
			return err
		}
		defer tx.Rollback(ctx)
		if err := s.storeRepo.UpdateQuestionBundleStatusTx(ctx, tx, bundleID, "queued", "processing"); err != nil {
			if errors.Is(err, repository.ErrNotFound) {
				return nil
			}
			return err
		}
		if err := tx.Commit(ctx); err != nil {
			return err
		}
	}

	objectKey, genErr := s.renderAndUploadQuestionBundle(ctx, bundle)
	tx, err := s.storeRepo.BeginTx(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	if genErr != nil {
		if err := s.storeRepo.UpdateQuestionBundleFailedTx(ctx, tx, bundleID, questionBundleUserError(genErr)); err != nil {
			if errors.Is(err, repository.ErrNotFound) {
				return nil
			}
			return err
		}
		return tx.Commit(ctx)
	}
	if err := s.storeRepo.UpdateQuestionBundleReadyTx(ctx, tx, bundleID, objectKey); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

func (s *Service) renderAndUploadQuestionBundle(ctx context.Context, bundle *model.QuestionBundle) (string, error) {
	if s.renderer == nil {
		return "", fmt.Errorf("pdf renderer not configured")
	}
	if s.storage == nil || s.cfg == nil || s.cfg.ObjectStorageBucketName == "" {
		return "", ErrStorageNotConfigured
	}

	tests, title, err := s.questionBundleTests(ctx, bundle)
	if err != nil {
		return "", err
	}
	html, err := buildQuestionBundleHTML(bundle, title, tests, func(stored string) string {
		return s.loadableQuestionAssetURL(ctx, stored)
	})
	if err != nil {
		return "", err
	}
	pdf, err := s.renderer.RenderHTML(ctx, html)
	if err != nil {
		return "", err
	}

	key := fmt.Sprintf("question-bundles/%s.pdf", bundle.ID)
	if _, err := s.storage.PutObject(ctx, s.cfg.ObjectStorageBucketName, key, bytes.NewReader(pdf), int64(len(pdf)), minio.PutObjectOptions{ContentType: questionBundlePDFContentType}); err != nil {
		return "", err
	}
	return key, nil
}

func (s *Service) questionBundleTests(ctx context.Context, bundle *model.QuestionBundle) ([]model.TestDetail, string, error) {
	if bundle.ExamID != nil {
		exam, err := s.storeRepo.GetExamByID(ctx, *bundle.ExamID)
		if err != nil {
			return nil, "", err
		}
		tests, err := s.storeRepo.GetSessionWithQuestions(ctx, *bundle.ExamID)
		if err != nil {
			return nil, "", err
		}
		return tests, exam.Title, nil
	}
	if bundle.TestID != nil {
		test, err := s.storeRepo.GetTestDetail(ctx, *bundle.TestID)
		if err != nil {
			return nil, "", err
		}
		return []model.TestDetail{*test}, test.Test.Title, nil
	}
	return nil, "", fmt.Errorf("%w: bundle has no scope", ErrValidation)
}

func buildQuestionBundleHTML(bundle *model.QuestionBundle, title string, tests []model.TestDetail, resolveAsset func(string) string) ([]byte, error) {
	if resolveAsset == nil {
		resolveAsset = func(stored string) string { return stored }
	}
	data := questionBundleHTMLData{
		Title:            title,
		BundleID:         bundle.ID.String(),
		CreatedBy:        bundle.CreatedBy.String(),
		IncludeAnswerKey: bundle.Variant == "kunci",
		Tests:            make([]questionBundleTestHTMLData, 0, len(tests)),
	}
	for _, test := range tests {
		td := questionBundleTestHTMLData{
			Title:           test.Test.Title,
			Subject:         test.Test.Subject,
			Topic:           test.Test.Topic,
			DurationMinutes: test.Test.DurationMinutes,
			Questions:       make([]questionBundleQuestionHTMLData, 0, len(test.Questions)),
		}
		for idx, q := range test.Questions {
			td.Questions = append(td.Questions, questionBundleQuestionData(idx+1, q, resolveAsset))
		}
		data.Tests = append(data.Tests, td)
	}

	var buf bytes.Buffer
	if err := questionBundleHTMLTemplate.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func questionBundleQuestionData(number int, q model.QuestionWithOptions, resolveAsset func(string) string) questionBundleQuestionHTMLData {
	out := questionBundleQuestionHTMLData{
		Number:       number,
		Format:       q.Question.Format,
		BodyHTML:     template.HTML(sanitizeQuestionBody(q.Question.Body)),
		PointCorrect: trimFloat(q.Question.PointCorrect),
		PointWrong:   trimFloat(q.Question.PointWrong),
	}
	if q.Question.ImageURL != nil {
		out.ImageURL = resolveAsset(*q.Question.ImageURL)
	}
	out.HasAudio = q.Question.AudioURL != nil && *q.Question.AudioURL != ""
	for _, opt := range q.Options {
		option := questionBundleOptionHTMLData{Key: strings.ToUpper(opt.Key), Text: opt.Text}
		if opt.ImageURL != nil {
			option.ImageURL = resolveAsset(*opt.ImageURL)
		}
		out.Options = append(out.Options, option)
		if opt.IsCorrect {
			out.CorrectOptions = appendCSV(out.CorrectOptions, strings.ToUpper(opt.Key))
		}
	}
	if q.Question.CorrectAnswer != nil {
		out.CorrectAnswer = *q.Question.CorrectAnswer
	}
	if len(q.Question.AcceptedAnswers) > 0 {
		out.AcceptedAnswers = strings.Join(q.Question.AcceptedAnswers, ", ")
	}
	for _, blank := range q.Blanks {
		value := blank.CorrectAnswer
		if len(blank.AcceptedAnswers) > 0 {
			value += " (diterima: " + strings.Join(blank.AcceptedAnswers, ", ") + ")"
		}
		out.Blanks = append(out.Blanks, value)
	}
	for _, stmt := range q.Question.Statements {
		out.PromptStatements = append(out.PromptStatements, stmt.Body)
		truth := "Salah"
		if stmt.IsTrue {
			truth = "Benar"
		}
		out.Statements = append(out.Statements, fmt.Sprintf("%s — %s", stmt.Body, truth))
	}
	if q.Question.Explanation != nil {
		out.Explanation = *q.Question.Explanation
	}
	out.HasKeyMaterial = out.CorrectOptions != "" || out.CorrectAnswer != "" || out.AcceptedAnswers != "" || len(out.Blanks) > 0 || len(out.Statements) > 0 || out.Explanation != ""
	return out
}

func appendCSV(existing, value string) string {
	if existing == "" {
		return value
	}
	return existing + ", " + value
}

func questionBundleUserError(err error) string {
	if err == nil {
		return "Gagal membuat PDF."
	}
	if errors.Is(err, ErrStorageNotConfigured) {
		return "Penyimpanan PDF belum siap. Coba lagi nanti."
	}
	return "Gagal membuat PDF. Coba lagi nanti."
}

func trimFloat(value float64) string {
	return strings.TrimRight(strings.TrimRight(fmt.Sprintf("%.2f", value), "0"), ".")
}

func (s *Service) loadableQuestionAssetURL(ctx context.Context, stored string) string {
	key := questionAssetKeyFromStored(stored)
	if key == "" || s.storage == nil || s.cfg == nil || s.cfg.ObjectStorageBucketName == "" {
		return stored
	}
	signed, err := s.presignInternalReadURL(ctx, s.cfg.ObjectStorageBucketName, key, presignedDocumentURLTTL)
	if err != nil {
		return stored
	}
	return signed
}

func questionAssetKeyFromStored(stored string) string {
	if strings.HasPrefix(stored, "question/") {
		return stored
	}
	marker := "/files/"
	idx := strings.Index(stored, marker)
	if idx < 0 {
		return ""
	}
	key := strings.TrimPrefix(stored[idx+len(marker):], "/")
	if strings.HasPrefix(key, "question/") {
		return key
	}
	return ""
}

// GetQuestionBundle fetches bundle metadata for status polling.
func (s *Service) GetQuestionBundle(ctx context.Context, bundleID uuid.UUID, actor uuid.UUID, actorRole string) (*model.QuestionBundle, error) {
	if !HasCapability(actorRole, "question-bundles:*") {
		return nil, ErrForbidden
	}

	bundle, err := s.storeRepo.GetQuestionBundleByID(ctx, bundleID)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, repository.ErrNotFound
		}
		return nil, err
	}
	if actorRole == RoleAdminExam && bundle.CreatedBy != actor {
		return nil, repository.ErrNotFound
	}
	return bundle, nil
}

// GetQuestionBundleDownloadURL returns a fresh presigned download URL for a ready bundle.
// Records audit evidence. 409 if not ready, 403 if forbidden, 404 if not found.
func (s *Service) GetQuestionBundleDownloadURL(ctx context.Context, bundleID uuid.UUID, actor uuid.UUID, actorRole string) (string, error) {
	if !HasCapability(actorRole, "question-bundles:*") {
		return "", ErrForbidden
	}

	bundle, err := s.storeRepo.GetQuestionBundleByID(ctx, bundleID)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return "", repository.ErrNotFound
		}
		return "", err
	}
	if actorRole == RoleAdminExam && bundle.CreatedBy != actor {
		return "", repository.ErrNotFound
	}
	if bundle.Status != "ready" {
		return "", fmt.Errorf("%w: bundle status is %s, not ready", ErrValidation, bundle.Status)
	}
	if bundle.ObjectKey == nil {
		return "", fmt.Errorf("%w: ready bundle has no object_key", ErrValidation)
	}
	if s.storage == nil || s.cfg == nil || s.cfg.ObjectStorageBucketName == "" {
		return "", ErrStorageNotConfigured
	}

	presigned, err := s.presignReadURL(ctx, s.cfg.ObjectStorageBucketName, *bundle.ObjectKey, presignedDocumentURLTTL)
	if err != nil {
		return "", fmt.Errorf("presign download url: %w", err)
	}

	actorStr := actor.String()
	if err := s.storeRepo.InsertAuditLogMeta(ctx, nil, &actorStr, "question_bundle", bundleID.String(), "question_bundle.download_url_issued", map[string]any{
		"variant": bundle.Variant,
	}); err != nil {
		return "", fmt.Errorf("audit question bundle download: %w", err)
	}
	return presigned, nil
}
